//! CLI-local strkey super-type generated by the [`strkey_enum!`] macro.
//!
//! The library intentionally does not ship a concrete super-type; the CLI
//! defines its own here to support decoding any strkey kind from a string
//! and (de)serializing them as JSON with hex byte fields.

use crate::{
    ed25519, strkey::strkey_enum, ClaimableBalance, Contract, HashX, LiquidityPool, PreAuthTx,
    Unredacted,
};

strkey_enum! {
    pub enum Strkey {
        PublicKeyEd25519(ed25519::PublicKey),
        PrivateKeyEd25519(Unredacted<ed25519::PrivateKey>),
        PreAuthTx(PreAuthTx),
        HashX(HashX),
        MuxedAccountEd25519(ed25519::MuxedAccount),
        SignedPayloadEd25519(ed25519::SignedPayload),
        Contract(Contract),
        LiquidityPool(LiquidityPool),
        ClaimableBalance(ClaimableBalance),
    }
}
